-- 1. Tutorial Groups (5 Groups)
INSERT INTO Tutorial_Groups (tg_number, ta_name) VALUES 
('T1', 'Alan Turing'), ('T2', 'Ada Lovelace'), ('T3', 'Grace Hopper'), 
('T4', 'John von Neumann'), ('T5', 'Katherine Johnson');

-- 2. Users (1 Admin + 44 Students spread across 5 TGs)
INSERT INTO Users (name, email, role, tg_id) VALUES 
('Tanish Jindal', 'tanish24579@iiitd.ac.in', 'Admin', 1),
('Aarav Sharma', 'aarav@iiitd.ac.in', 'Student', 1),
('Aditi Verma', 'aditi@iiitd.ac.in', 'Student', 1),
('Aditya Singh', 'aditya@iiitd.ac.in', 'Student', 1),
('Akhil Reddy', 'akhil@iiitd.ac.in', 'Student', 1),
('Anjali Desai', 'anjali@iiitd.ac.in', 'Student', 1),
('Ansh Kumar', 'ansh@iiitd.ac.in', 'Student', 1),
('Aryan Gupta', 'aryan@iiitd.ac.in', 'Student', 1),
('Ayush Patel', 'ayush@iiitd.ac.in', 'Student', 1),
('Bhavya Joshi', 'bhavya@iiitd.ac.in', 'Student', 1),
('Chaitanya Rao', 'chaitanya@iiitd.ac.in', 'Student', 2),
('Deepak Kumar', 'deepak@iiitd.ac.in', 'Student', 2),
('Dev Shah', 'dev@iiitd.ac.in', 'Student', 2),
('Dhruv Nair', 'dhruv@iiitd.ac.in', 'Student', 2),
('Diya Mehta', 'diya@iiitd.ac.in', 'Student', 2),
('Esha Singh', 'esha@iiitd.ac.in', 'Student', 2),
('Gaurav Das', 'gaurav@iiitd.ac.in', 'Student', 2),
('Harsha Vardhan', 'harsha@iiitd.ac.in', 'Student', 2),
('Ishaan Ali', 'ishaan@iiitd.ac.in', 'Student', 2),
('Jay Krishnan', 'jay@iiitd.ac.in', 'Student', 3),
('Kabir Khan', 'kabir@iiitd.ac.in', 'Student', 3),
('Karan Malhotra', 'karan@iiitd.ac.in', 'Student', 3),
('Kartik Iyer', 'kartik@iiitd.ac.in', 'Student', 3),
('Kavya Pillai', 'kavya@iiitd.ac.in', 'Student', 3),
('Krish Agarwal', 'krish@iiitd.ac.in', 'Student', 3),
('Kunal Bhatia', 'kunal@iiitd.ac.in', 'Student', 3),
('Lakshya Sen', 'lakshya@iiitd.ac.in', 'Student', 3),
('Madhav Raj', 'madhav@iiitd.ac.in', 'Student', 3),
('Manan Jain', 'manan@iiitd.ac.in', 'Student', 4),
('Megha Bose', 'megha@iiitd.ac.in', 'Student', 4),
('Mihir Roy', 'mihir@iiitd.ac.in', 'Student', 4),
('Mukul Anand', 'mukul@iiitd.ac.in', 'Student', 4),
('Neha Kapoor', 'neha@iiitd.ac.in', 'Student', 4),
('Nikhil Varma', 'nikhil@iiitd.ac.in', 'Student', 4),
('Nisha Yadav', 'nisha@iiitd.ac.in', 'Student', 4),
('Om Prakash', 'om@iiitd.ac.in', 'Student', 4),
('Parth Saxena', 'parth@iiitd.ac.in', 'Student', 5),
('Pooja Rani', 'pooja@iiitd.ac.in', 'Student', 5),
('Pranav Menon', 'pranav@iiitd.ac.in', 'Student', 5),
('Rahul Tiwari', 'rahul@iiitd.ac.in', 'Student', 5),
('Riya Pandey', 'riya@iiitd.ac.in', 'Student', 5),
('Rohan Chawla', 'rohan@iiitd.ac.in', 'Student', 5),
('Sahil Soni', 'sahil@iiitd.ac.in', 'Student', 5),
('Sameer Khan', 'sameer@iiitd.ac.in', 'Student', 5),
('Ghost User', 'ghost@iiitd.ac.in', 'Student', 5);

-- 3. Topics (40 Topics - Heavy on CS, Math, and Software Engineering)
INSERT INTO Topics (topic_name, is_active, admin_id) VALUES 
('Data Structures and Algorithms', 1, 1),
('Database Management Systems (DBMS)', 1, 1),
('Statistical Machine Learning (SML)', 1, 1),
('Theory of Computation (DFA)', 1, 1),
('Ordinary Differential Equations', 1, 1),
('Advanced Java & Multithreading', 1, 1),
('C/C++ System Programming', 1, 1),
('Full Stack Web Dev (React & Node)', 1, 1),
('Spring Boot Architecture', 1, 1),
('Operating Systems', 1, 1),
('Computer Networks', 1, 1),
('Discrete Mathematics', 1, 1),
('Linear Algebra', 1, 1),
('Probability & Statistics', 1, 1),
('Machine Learning Basics', 1, 1),
('Deep Learning', 1, 1),
('Computer Vision', 1, 1),
('Natural Language Processing', 1, 1),
('Cryptography', 1, 1),
('Network Security', 1, 1),
('Cloud Computing', 1, 1),
('Distributed Systems', 1, 1),
('Parallel Programming', 1, 1),
('Software Engineering Principles', 1, 1),
('Compiler Design', 1, 1),
('Algorithm Analysis', 1, 1),
('Mobile App Development', 1, 1),
('Game Development', 1, 1),
('Quantum Computing', 1, 1),
('Information Retrieval', 1, 1),
('Data Mining', 1, 1),
('Bioinformatics', 1, 1),
('Robotics', 1, 1),
('Computer Graphics', 1, 1),
('Software Testing', 1, 1),
('Cyber Security', 1, 1),
('Blockchain Technologies', 1, 1),
('Internet of Things (IoT)', 1, 1),
('Embedded Systems', 1, 1),
('2024 Legacy Midsem Prep', 0, 1); -- Legacy topic for Query 14

-- 4. Website Categories
INSERT INTO Website_Categories (category_name, penalty_weight, admin_id) VALUES 
('Productive', 0, 1), 
('Distracting', 15, 1);

-- 5. Category Keywords (15 Keywords)
INSERT INTO Category_Keywords (keyword, wc_id) VALUES 
('VS Code', 1), ('IntelliJ IDEA', 1), ('LeetCode', 1), ('GeeksforGeeks', 1), 
('Stack Overflow', 1), ('GitHub', 1), ('Localhost', 1), ('MySQL Workbench', 1),
('YouTube', 2), ('Netflix', 2), ('Instagram', 2), ('Twitter', 2), 
('Reddit', 2), ('WhatsApp', 2), ('Discord', 2);

-- 6. Sessions (50 Sessions across different users, topics, and dates)
INSERT INTO Sessions (u_id, topic_id, start_time, status, goal) VALUES 
(2, 1, NOW() - INTERVAL 1 DAY, 'completed', 'Solve Striver A2Z'),
(3, 2, NOW() - INTERVAL 2 DAY, 'completed', 'SQL Queries Task'),
(4, 3, NOW() - INTERVAL 3 HOUR, 'completed', 'SML Assignment'),
(5, 4, NOW() - INTERVAL 1 HOUR, 'completed', 'DFA state proofs'),
(6, 5, NOW() - INTERVAL 4 DAY, 'completed', 'ODE modification rules'),
(7, 6, NOW() - INTERVAL 5 DAY, 'completed', 'Java ReentrantLock practice'),
(8, 7, NOW() - INTERVAL 12 HOUR, 'completed', 'C Shell assignment'),
(9, 8, NOW() - INTERVAL 2 DAY, 'completed', 'Expense Tracker Frontend'),
(10, 9, NOW() - INTERVAL 1 DAY, 'completed', 'Spring Boot API'),
(11, 10, NOW() - INTERVAL 6 DAY, 'completed', 'Process execution stack'),
(12, 1, NOW() - INTERVAL 7 DAY, 'completed', 'LeetCode Array series'),
(13, 2, NOW() - INTERVAL 2 HOUR, 'completed', 'Normalize database to 3NF'),
(14, 3, NOW() - INTERVAL 1 DAY, 'completed', 'Gradient Descent math'),
(15, 4, NOW() - INTERVAL 3 DAY, 'completed', 'Closure properties DFA'),
(16, 5, NOW() - INTERVAL 4 HOUR, 'completed', 'Sturm-Liouville problems'),
(17, 6, NOW() - INTERVAL 8 DAY, 'completed', 'Library Management System'),
(18, 7, NOW() - INTERVAL 9 DAY, 'completed', 'ELF file format research'),
(19, 8, NOW() - INTERVAL 1 DAY, 'completed', 'React components'),
(20, 9, NOW() - INTERVAL 2 DAY, 'completed', 'Remove docker from project'),
(21, 1, NOW(), 'active', 'Dynamic Programming'),
(22, 2, NOW(), 'active', 'MySQL Indexing'),
(23, 3, NOW(), 'active', 'Study for SML quiz'),
(24, 8, NOW(), 'active', 'Node server debugging'),
(25, 40, NOW() - INTERVAL 10 DAY, 'completed', 'Old prep material'),
(26, 1, NOW() - INTERVAL 5 HOUR, 'completed', 'Graph Traversal'),
(27, 2, NOW() - INTERVAL 6 HOUR, 'completed', 'Database Triggers'),
(28, 3, NOW() - INTERVAL 7 HOUR, 'completed', 'Linear Regression'),
(29, 4, NOW() - INTERVAL 8 HOUR, 'completed', 'Turing Machines'),
(30, 5, NOW() - INTERVAL 9 HOUR, 'completed', 'Calculus review'),
(31, 6, NOW() - INTERVAL 10 HOUR, 'completed', 'Stock Trading Simulator'),
(32, 7, NOW() - INTERVAL 11 HOUR, 'completed', 'Pointers in C'),
(33, 8, NOW() - INTERVAL 12 HOUR, 'completed', 'CSS Styling'),
(34, 9, NOW() - INTERVAL 13 HOUR, 'completed', 'Java Exceptions'),
(35, 10, NOW() - INTERVAL 14 HOUR, 'completed', 'Memory Management'),
(36, 1, NOW() - INTERVAL 15 HOUR, 'completed', 'Binary Trees'),
(37, 2, NOW() - INTERVAL 16 HOUR, 'completed', 'JOIN queries'),
(38, 3, NOW() - INTERVAL 17 HOUR, 'completed', 'Neural Networks'),
(39, 4, NOW() - INTERVAL 18 HOUR, 'completed', 'Context Free Grammars'),
(40, 5, NOW() - INTERVAL 19 HOUR, 'completed', 'Differential Equations'),
(41, 1, NOW() - INTERVAL 20 HOUR, 'completed', 'Sorting algorithms'),
(42, 2, NOW() - INTERVAL 21 HOUR, 'completed', 'ER Diagrams'),
(43, 3, NOW() - INTERVAL 22 HOUR, 'completed', 'Data preprocessing'),
(44, 4, NOW() - INTERVAL 23 HOUR, 'completed', 'Automata construction'),
(45, 5, NOW() - INTERVAL 24 HOUR, 'completed', 'Math assignment'),
(46, 40, NOW() - INTERVAL 14 DAY, 'completed', 'Ghost User Session'),
(2, 6, NOW() - INTERVAL 2 DAY, 'completed', 'Java JFrame setup'),
(3, 8, NOW() - INTERVAL 3 DAY, 'completed', 'Web Dev portfolio'),
(4, 1, NOW() - INTERVAL 4 DAY, 'completed', 'SDE Intern Prep'),
(5, 2, NOW() - INTERVAL 5 DAY, 'completed', 'Learn MongoDB transition');

-- 7. Activity Logs (Over 100 Logs generating mixed productivity metrics)
-- We map these logs to the sessions (s_id 1 to 50) and keywords (ck_id 1 to 15)
INSERT INTO Activity_Logs (s_id, ck_id, window_title, timestamp, duration) VALUES 
-- Session 1 (Productive)
(1, 3, 'LeetCode - Chrome', NOW() - INTERVAL 1 DAY + INTERVAL 1 MINUTE, 10),
(1, 1, 'Solution.java - VS Code', NOW() - INTERVAL 1 DAY + INTERVAL 2 MINUTE, 15),
(1, 4, 'GeeksforGeeks arrays - Chrome', NOW() - INTERVAL 1 DAY + INTERVAL 3 MINUTE, 10),
-- Session 2 (Mixed)
(2, 8, 'MySQL Workbench', NOW() - INTERVAL 2 DAY + INTERVAL 1 MINUTE, 10),
(2, 5, 'Stack Overflow SQL join', NOW() - INTERVAL 2 DAY + INTERVAL 2 MINUTE, 5),
(2, 9, 'YouTube - Funny video', NOW() - INTERVAL 2 DAY + INTERVAL 5 MINUTE, 5),
(2, 11, 'Instagram Reels', NOW() - INTERVAL 2 DAY + INTERVAL 10 MINUTE, 10),
-- Session 3 (Very Productive)
(3, 1, 'sml_model.py - VS Code', NOW() - INTERVAL 3 HOUR + INTERVAL 1 MINUTE, 20),
(3, 6, 'GitHub Repo - Chrome', NOW() - INTERVAL 3 HOUR + INTERVAL 5 MINUTE, 10),
-- Session 4 (Mixed)
(4, 1, 'dfa_proof.pdf - VS Code', NOW() - INTERVAL 1 HOUR + INTERVAL 1 MINUTE, 5),
(4, 14, 'WhatsApp Web', NOW() - INTERVAL 1 HOUR + INTERVAL 2 MINUTE, 10),
-- Session 5 (Productive)
(5, 1, 'math_notes.txt - VS Code', NOW() - INTERVAL 4 DAY + INTERVAL 1 MINUTE, 20),
-- Session 6 (Distracted)
(6, 2, 'Main.java - IntelliJ IDEA', NOW() - INTERVAL 5 DAY + INTERVAL 1 MINUTE, 5),
(6, 10, 'Netflix - Alice in Borderland', NOW() - INTERVAL 5 DAY + INTERVAL 5 MINUTE, 30),
-- Session 7 (Productive)
(7, 1, 'shell.c - VS Code', NOW() - INTERVAL 12 HOUR + INTERVAL 1 MINUTE, 15),
(7, 5, 'Stack Overflow fork()', NOW() - INTERVAL 12 HOUR + INTERVAL 2 MINUTE, 10),
-- Session 8 (Mixed)
(8, 1, 'App.jsx - VS Code', NOW() - INTERVAL 2 DAY + INTERVAL 1 MINUTE, 10),
(8, 7, 'Localhost:3000', NOW() - INTERVAL 2 DAY + INTERVAL 2 MINUTE, 10),
(8, 13, 'Reddit r/webdev', NOW() - INTERVAL 2 DAY + INTERVAL 5 MINUTE, 5),
-- Session 21 (Active right now)
(21, 3, 'LeetCode DP - Chrome', NOW() - INTERVAL 5 MINUTE, 5),
(21, 1, 'dp.cpp - VS Code', NOW() - INTERVAL 1 MINUTE, 5),
-- Session 22 (Active right now, highly distracted)
(22, 8, 'MySQL Workbench', NOW() - INTERVAL 10 MINUTE, 5),
(22, 12, 'Twitter feed', NOW() - INTERVAL 5 MINUTE, 5),
(22, 9, 'YouTube - LoFi Girl', NOW() - INTERVAL 1 MINUTE, 5),
-- Session 46 (Ghost User, 14 days ago)
(46, 1, 'notes - VS Code', NOW() - INTERVAL 14 DAY + INTERVAL 1 MINUTE, 20),
-- Session 49 (SDE Prep - Extremely Productive > 30 units)
(49, 3, 'LeetCode Hard - Chrome', NOW() - INTERVAL 4 DAY + INTERVAL 1 MINUTE, 15),
(49, 1, 'Solution.java - VS Code', NOW() - INTERVAL 4 DAY + INTERVAL 2 MINUTE, 15),
(49, 4, 'Striver Sheet - GeeksforGeeks', NOW() - INTERVAL 4 DAY + INTERVAL 3 MINUTE, 10);
INSERT INTO Activity_Logs (s_id, ck_id, window_title, timestamp, duration) VALUES 
-- Session 1 to 5 (Striver, SQL, SML, DFA, ODE)
(1, 3, 'LeetCode - Chrome', NOW() - INTERVAL 1 DAY + INTERVAL 1 MINUTE, 10),
(1, 1, 'Solution.java - VS Code', NOW() - INTERVAL 1 DAY + INTERVAL 2 MINUTE, 15),
(1, 4, 'GeeksforGeeks arrays - Chrome', NOW() - INTERVAL 1 DAY + INTERVAL 3 MINUTE, 10),
(2, 8, 'MySQL Workbench', NOW() - INTERVAL 2 DAY + INTERVAL 1 MINUTE, 10),
(2, 5, 'Stack Overflow SQL join', NOW() - INTERVAL 2 DAY + INTERVAL 2 MINUTE, 5),
(2, 9, 'YouTube - Funny video', NOW() - INTERVAL 2 DAY + INTERVAL 5 MINUTE, 5),
(3, 1, 'sml_model.py - VS Code', NOW() - INTERVAL 3 HOUR + INTERVAL 1 MINUTE, 20),
(3, 6, 'GitHub Repo - Chrome', NOW() - INTERVAL 3 HOUR + INTERVAL 5 MINUTE, 10),
(4, 1, 'dfa_proof.pdf - VS Code', NOW() - INTERVAL 1 HOUR + INTERVAL 1 MINUTE, 5),
(4, 14, 'WhatsApp Web', NOW() - INTERVAL 1 HOUR + INTERVAL 2 MINUTE, 10),
(5, 1, 'math_notes.txt - VS Code', NOW() - INTERVAL 4 DAY + INTERVAL 1 MINUTE, 20),

-- Session 6 to 10 (Java, C Shell, React, Spring Boot)
(6, 2, 'Main.java - IntelliJ IDEA', NOW() - INTERVAL 5 DAY + INTERVAL 1 MINUTE, 5),
(6, 10, 'Netflix - Alice in Borderland', NOW() - INTERVAL 5 DAY + INTERVAL 5 MINUTE, 30),
(7, 1, 'shell.c - VS Code', NOW() - INTERVAL 12 HOUR + INTERVAL 1 MINUTE, 15),
(7, 5, 'Stack Overflow fork()', NOW() - INTERVAL 12 HOUR + INTERVAL 2 MINUTE, 10),
(8, 1, 'App.jsx - VS Code', NOW() - INTERVAL 2 DAY + INTERVAL 1 MINUTE, 10),
(8, 7, 'Localhost:3000', NOW() - INTERVAL 2 DAY + INTERVAL 2 MINUTE, 10),
(8, 13, 'Reddit r/webdev', NOW() - INTERVAL 2 DAY + INTERVAL 5 MINUTE, 5),
(9, 2, 'SpringApplication - IntelliJ', NOW() - INTERVAL 1 DAY + INTERVAL 5 MINUTE, 20),
(9, 5, 'Stack Overflow JPA', NOW() - INTERVAL 1 DAY + INTERVAL 10 MINUTE, 10),
(10, 1, 'stack_trace.txt - VS Code', NOW() - INTERVAL 6 DAY + INTERVAL 1 MINUTE, 15),

-- Session 11 to 20 (General Coursework & Projects)
(11, 3, 'LeetCode Arrays - Chrome', NOW() - INTERVAL 7 DAY + INTERVAL 5 MINUTE, 25),
(12, 8, 'MySQL Workbench', NOW() - INTERVAL 2 HOUR + INTERVAL 10 MINUTE, 15),
(12, 11, 'Instagram - Scrolling', NOW() - INTERVAL 2 HOUR + INTERVAL 15 MINUTE, 20),
(13, 1, 'math_derivation.pdf', NOW() - INTERVAL 1 DAY + INTERVAL 2 MINUTE, 10),
(14, 1, 'dfa_notes.txt', NOW() - INTERVAL 3 DAY + INTERVAL 1 MINUTE, 15),
(15, 1, 'equations.pdf', NOW() - INTERVAL 4 HOUR + INTERVAL 1 MINUTE, 10),
(16, 2, 'LibrarySystem.java - IntelliJ', NOW() - INTERVAL 8 DAY + INTERVAL 5 MINUTE, 20),
(17, 1, 'elf_format.pdf', NOW() - INTERVAL 9 DAY + INTERVAL 2 MINUTE, 15),
(18, 1, 'Navbar.jsx - VS Code', NOW() - INTERVAL 1 DAY + INTERVAL 5 MINUTE, 10),
(19, 1, 'docker-compose.yml', NOW() - INTERVAL 2 DAY + INTERVAL 1 MINUTE, 10),
(20, 9, 'YouTube - LoFi Girl', NOW() - INTERVAL 2 DAY + INTERVAL 5 MINUTE, 30),

-- Session 21 to 24 (ACTIVE Sessions - Occurring right now)
(21, 3, 'LeetCode DP - Chrome', NOW() - INTERVAL 5 MINUTE, 5),
(21, 1, 'dp.cpp - VS Code', NOW() - INTERVAL 1 MINUTE, 5),
(22, 8, 'MySQL Workbench', NOW() - INTERVAL 10 MINUTE, 5),
(22, 12, 'Twitter feed', NOW() - INTERVAL 5 MINUTE, 5),
(23, 1, 'sml_notes.pdf', NOW() - INTERVAL 2 MINUTE, 10),
(24, 1, 'server.js - VS Code', NOW() - INTERVAL 4 MINUTE, 10),
(24, 7, 'Localhost:8080', NOW() - INTERVAL 1 MINUTE, 5),

-- Session 25 to 40 (Midsem Prep & Various Topics)
(25, 1, 'old_notes.txt', NOW() - INTERVAL 10 DAY + INTERVAL 5 MINUTE, 15),
(26, 3, 'LeetCode Graphs', NOW() - INTERVAL 5 HOUR + INTERVAL 1 MINUTE, 20),
(27, 8, 'MySQL Workbench', NOW() - INTERVAL 6 HOUR + INTERVAL 5 MINUTE, 15),
(28, 1, 'linear_reg.py', NOW() - INTERVAL 7 HOUR + INTERVAL 2 MINUTE, 10),
(29, 1, 'turing.pdf', NOW() - INTERVAL 8 HOUR + INTERVAL 5 MINUTE, 10),
(30, 9, 'YouTube - Math Tutorial', NOW() - INTERVAL 9 HOUR + INTERVAL 1 MINUTE, 20),
(31, 2, 'TradingSim.java', NOW() - INTERVAL 10 HOUR + INTERVAL 5 MINUTE, 25),
(32, 1, 'pointers.c', NOW() - INTERVAL 11 HOUR + INTERVAL 10 MINUTE, 15),
(33, 1, 'styles.css', NOW() - INTERVAL 12 HOUR + INTERVAL 2 MINUTE, 10),
(33, 15, 'Discord - Chatting', NOW() - INTERVAL 12 HOUR + INTERVAL 15 MINUTE, 20),
(34, 2, 'ExceptionTest.java', NOW() - INTERVAL 13 HOUR + INTERVAL 5 MINUTE, 10),
(35, 1, 'memory.c', NOW() - INTERVAL 14 HOUR + INTERVAL 1 MINUTE, 15),
(36, 4, 'GeeksforGeeks Trees', NOW() - INTERVAL 15 HOUR + INTERVAL 2 MINUTE, 10),
(37, 8, 'MySQL Workbench', NOW() - INTERVAL 16 HOUR + INTERVAL 5 MINUTE, 20),
(38, 1, 'neural_net.py', NOW() - INTERVAL 17 HOUR + INTERVAL 10 MINUTE, 15),
(39, 1, 'cfg_rules.txt', NOW() - INTERVAL 18 HOUR + INTERVAL 2 MINUTE, 10),
(40, 1, 'diff_eq.pdf', NOW() - INTERVAL 19 HOUR + INTERVAL 5 MINUTE, 15),

-- Session 41 to 50 (Wrapping up the remaining students)
(41, 3, 'LeetCode Sorting', NOW() - INTERVAL 20 HOUR + INTERVAL 5 MINUTE, 20),
(42, 1, 'diagram.png', NOW() - INTERVAL 21 HOUR + INTERVAL 1 MINUTE, 10),
(43, 1, 'data_clean.py', NOW() - INTERVAL 22 HOUR + INTERVAL 5 MINUTE, 15),
(44, 1, 'automata.pdf', NOW() - INTERVAL 23 HOUR + INTERVAL 2 MINUTE, 10),
(45, 1, 'math_hw.pdf', NOW() - INTERVAL 24 HOUR + INTERVAL 10 MINUTE, 20),
(46, 1, 'notes - VS Code', NOW() - INTERVAL 14 DAY + INTERVAL 1 MINUTE, 20),
(47, 2, 'JFrame.java - IntelliJ', NOW() - INTERVAL 2 DAY + INTERVAL 5 MINUTE, 15),
(48, 1, 'portfolio.html', NOW() - INTERVAL 3 DAY + INTERVAL 2 MINUTE, 10),
(49, 3, 'LeetCode Hard - Chrome', NOW() - INTERVAL 4 DAY + INTERVAL 1 MINUTE, 15),
(49, 1, 'Solution.java - VS Code', NOW() - INTERVAL 4 DAY + INTERVAL 2 MINUTE, 15),
(49, 4, 'Striver Sheet - GeeksforGeeks', NOW() - INTERVAL 4 DAY + INTERVAL 3 MINUTE, 10),
(50, 1, 'mongodb_docs.pdf', NOW() - INTERVAL 5 DAY + INTERVAL 5 MINUTE, 20);

INSERT INTO Store_Items (name, description, cost, icon) VALUES 
('Custom Profile Badges', 'Badges like "Algorithm Ace" or "Deep Work Demon" that sit next to your name.', 300, '🏅'),
('"Night Owl" Theme', 'Unlocks a pure-black dark mode for the dashboard.', 500, '🌙'),
('Golden Username', 'Your name glows gold on the Global Leaderboard.', 1000, '✨'),
('1-on-1 Mentorship Session', 'A 15-minute private Zoom call with the TA.', 1500, '🤝'),
('Free Coffee Voucher', 'A coupon code for the campus cafe.', 2000, '☕'),
('Assignment 24-Hour Extension', 'A "get out of jail free" card for a late submission.', 2500, '⏰'),
('Pizza Slice', 'A free slice of pizza to fuel your next study session.', 3000, '🍕'),
('Skip One Small Quiz', 'The ultimate grind goal. Pass "Go" and collect your A.', 5000, '👑');
